#!/bin/bash
backuplog="/usr/local/var/log/backup.log"
repo="/Volumes/ColdStorage"
attached=$(df | awk '{print $NF}' | grep -Ex $repo) 

if [[ $attached == "/Volumes/ColdStorage" ]]; then
	/usr/local/bin/restic backup -e "*.vmdk" -r $repo /Users/damien  >> $backuplog && echo "Last backup taken $(date)" >> $backuplog
else
	echo "Backup drive not attached. Skipping..." >> $backuplog
fi
