#!/bin/bash
backuplog="/usr/local/var/log/backup.log"
repo="/Volumes/ColdStorage"
attached=$(df | awk '{print $NF}' | grep -Ex $repo)
pdir="/Users/damien/.pw/restic.txt"

if [[ $attached == "/Volumes/ColdStorage" ]]; then
	/usr/local/bin/restic backup -p $pdir -e "*.vmdk" -e "*.qcow2" -r $repo /Users/damien  >> $backuplog && echo "Last backup taken $(date)" >> $backuplog
else
	echo "Backup drive not attached. Skipping..." >> $backuplog
fi
