#!/bin/bash
backuplog="/usr/local/var/log/backup.log"
attached=$(df | awk '{print $NF}' | grep -Ex "/Volumes/ColdStorage") 

if [[ $attached == "/Volumes/ColdStorage" ]]; then
	/usr/local/bin/restic backup -e "*.vmdk" $HOME  >> $backuplog && echo "Last backup taken $(date)" >> $backuplog
else
	echo "Backup drive not attached. Skipping..." >> $backuplog
fi
