#!/bin/bash
echo "🌍  starting all databases..."
brew services start docker-machine && \
echo "✅  INT: Containers OK"
brew services start elasticsearch && \
echo "✅  IR: Enterprise OK"
brew services start influxdb && \
echo "✅  DB: TS OK"
brew services start postgresql && \
echo "✅  SQL OK"
brew services start solr
echo "✅  IR: OSS OK"