#!/bin/bash

code --install-extension LawrenceGrant.cql &&
code --install-extension Rubymaniac.vscode-html-to-elm &&
code --install-extension UCL.haskelly &&
code --install-extension andradei.minimal-colors &&
code --install-extension bungcip.better-toml &&
code --install-extension cazzar09.Gradle &&
code --install-extension codezombiech.gitignore &&
code --install-extension donjayamanne.python &&
code --install-extension goessner.mdmath &&
code --install-extension jack-pallot.vscode-theme-neat &&
code --install-extension justusadam.language-haskell &&
code --install-extension kalitaalexey.vscode-rust &&
code --install-extension lukehoban.Go &&
code --install-extension ms-vscode.cpptools &&
code --install-extension nwolverson.ide-purescript &&
code --install-extension nwolverson.language-purescript &&
code --install-extension oijaz.unicode-latex &&
code --install-extension redhat.java &&
code --install-extension sbrink.elm &&
code --install-extension shyykoserhiy.sockscode-vscode &&
code --install-extension vscodevim.vim &&
code --install-extension wayou.vscode-todo-highlight &&
code --install-extension zxh404.vscode-proto3