#!/bin/bash
cat <<I>> .gitignore
*.DS_Store
*.swp
*.o
*.so
env/
bin/
node_modules/
.vscode/
.idea/
vendor/*/*
target/
Cargo.lock
**/*.rs.bak
elm-stuff
repl-temp-*
.psci_modules
bower_components
node_modules
.psci
output
dist
dist-*
cabal-dev
*.hi
*.chi
*.chs.h
*.dyn_o
*.dyn_hi
.hpc
.hsenv
.cabal-sandbox/
cabal.sandbox.config
*.prof
*.aux
*.hp
*.eventlog
.stack-work/
cabal.project.local
.HTF/
I

name=${PWD##*/}
cat <<READ>> README.md
# $name

READ
