#!/bin/bash
cd $GOPATH && cd ../data_model

if [ $1 == "start" ]
then
	docker-compose up -d \
        && minikube start --insecure-registry "10.0.2.2:5000" --memory 6144
fi
if [ $1 == "stop" ]
then
	docker-compose kill && minikube stop
fi
if [ $1 == "cleanup" ]
then
    docker-compose rm -v && minikube delete
fi
