#!/bin/bash
# The morning routine. Right now, just runs a backup.
echo "👋  Good morning!"
echo
echo "Let's back up all the things..."
restic -r /Volumes/Storage/backups backup $HOME \
       && echo "Backup complete."
