#!/bin/bash
mkdir -p $1/lib && mkdir -p $1/test && cd $1 && \

cat <<IGNORE>> .gitignore
.vscode/
.idea/
env/
build/
node_modules
*.DS_Store
*.swp
*.o
IGNORE

cat <<README>> README.md
### $1

#### License

Copyright (c) 2017
README

python3 -m venv env && source env/bin/activate && \
	echo "⏳  building temporary environment..."
    pip3 install https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.1-py3-none-any.whl && \
    echo "🤖  TensorFlow installed"
	pip3 install matplotlib gym $TF_BINARY_URL keras numpy scipy pandas flask requests six jupyter ipython && \
	echo "📓  📊  Jupyter and required scientific libs installed"
	git clone https://github.com/openai/universe && cd universe && pip3 install -e . && cd .. && \
	echo "🌍  OpenAI Universe installed"
	jupyter notebook && deactivate && rm -rf env/
	echo "👌  temporary environment destroyed cleanly"
