#!/bin/bash
w=$1
u="damienstanton"
if [ -z "$1" ]; then
    echo -n "Need the name of the new repo:"
    read w
fi
curl -u $u https://api.github.com/user/repos -d "{\"name\":\"$w\"}"
git init && git remote add origin https://github.com/$u/$w
