#!/bin/bash
T=$1
mkdir -p $T/bin && \

cd $T && \
cat <<MAIN > main.go
package main

import "fmt"

// testInit is a test helper.
func testInit() (bool, error) {
	return true, nil
}

func main() {
	fmt.Println("OK")
}
MAIN

cat <<TEST > main_test.go
package main

import "testing"

func TestInit(t *testing.T) {
	h, err := testInit()
	if err != nil {
		t.Errorf("unexpected error: %v", err)
	}
	if !h {
		t.Fatal("init test failed")
	}
}
TEST

cat <<IGNORE>> .gitignore
bin/
vendor/*/*
.vscode/
.idea/
*.swp
*.o
*.so
IGNORE

cat <<LICENSE>> LICENSE
Copyright (c) 2017 DK Stanton Consulting, Inc. DBA Blink Analytics.
All Rights Reserved.
Unauthorized copying of this software, via any medium, is strictly prohibited.
LICENSE

go test -v -cover && go build -o bin/$T && \
echo "Go project $T setup complete. cd to $T/"
echo
