#!/bin/bash
WORKDIR=$1

mkdir $WORKDIR && cd $WORKDIR

echo "Creating new Scala project: $WORKDIR"

cat <<SBTFILE>> build.sbt
name := "$WORKDIR"
scalaVersion in ThisBuild := "2.12.3"
ensimeIgnoreMissingDirectories in ThisBuild := true

logBuffered in Test := false
cancelable in Global := true

libraryDependencies ++= Seq(
	"org.scalactic" %% "scalactic" % "3.0.1",
	"org.scalatest" %% "scalatest" % "3.0.1" % "test",
	"org.scalacheck" %% "scalacheck" % "1.13.4" % "test"
)
SBTFILE

cat <<IGNORE>> .gitignore
target/
project/
.ensime
.ensime_cache/
.cache/
*.log
IGNORE

mkdir -p src/main/scala
mkdir -p src/test/scala

cat <<SCALAFILE>> src/main/scala/App.scala

package $WORKDIR

object App {
  def main(args: Array[String]) = {
    println("$WORKDIR OK")
  }
}
SCALAFILE

sbt ensimeConfig
