#!/bin/bash
touch $1.sh && chmod +x $1.sh && \
cat <<SETUP>> $1.sh
#!/bin/bash

# pretty logging
# ---
# info
╔════╗
║ 🚀  ║
╚════╝
# pass
╔════╗
║ ✅  ║
╚════╝
# fail
╔════╗
║ ❌  ║
╚════╝

# vars
# ---

# tests
# ---

# commands
# ---
SETUP
vi $1.sh