#!/bin/bash
touch $1.sh && chmod +x $1.sh && \
cat <<SETUP>> $1.sh
#!/bin/bash

# pretty logging
# ---
# info
echo "╔════╗"
echo "║ 🚀  ║"
echo "╚════╝"
# pass
echo "╔════╗"
echo "║ ✅  ║"
echo "╚════╝"
# fail
echo "╔════╗"
echo "║ ❌  ║"
echo "╚════╝"

# vars
# ---

# tests
# ---

# commands
# ---

SETUP
vi $1.sh