#!/bin/bash
echo "Merging damienstanton/tensorflow with tensorflow/tensorflow"
cd $GOPATH/src/github.com/damienstanton/tensorflow \
	&& git fetch up master \
	&& git merge up/master \
	&& git push \

git checkout api15 \
	&& git merge origin/master
echo "api15 branch up-to-date"

git checkout golang \
	&& git merge origin/master
echo "golang branch up-to-date"
