#!/bin/bash
TF_TYPE="cpu"

echo "Downloading TensorFlow C headers to /usr/local..."
curl -L \
	  "https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-${TF_TYPE}-$(go env GOOS)-x86_64-1.0.0.tar.gz" |
sudo tar -C /usr/local -xz

echo "OK. Getting TensorFlow Go bindings..."
go get github.com/tensorflow/tensorflow/tensorflow/go
go test github.com/tensorflow/tensorflow/tensorflow/go
echo "Done."
